
//------------------------------------------------------------------------------
// This code was generated by a tool.
//
//   Tool : Bond Compiler 0.10.0.0
//   File : record_types.cpp
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// <auto-generated />
//------------------------------------------------------------------------------

#include "record_reflection.h"
#include <bond/core/exception.h>

namespace example
{
    
    const ::bond::Metadata Record::Schema::metadata
        = Record::Schema::GetMetadata();
    
    const ::bond::Metadata Record::Schema::s_name_metadata
        = ::bond::reflection::MetadataInit("name");
    
    const ::bond::Metadata Record::Schema::s_items_metadata
        = ::bond::reflection::MetadataInit("items");

    
} // namespace example
